# config for local development, with connection to saip infrastructure
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/blog_test_task
    username: "mykola"
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  liquibase:
    changeLog: classpath:config/liquibase/changelog-master.xml

  jwt:
    jwtSecret: scrt
    storedTokenLength: 7
    tokenExp: 864000000

  freemarker:
    template-loader-path: classpath:/templates/

springdoc:
  api-docs:
    path: /api-docs/v1

frontend:
  basepath: http://localhost:3000
